name: Deploy to Lyrid

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl https://api.lyrid.io/client/dl/linux --output /usr/local/bin/lc && chmod +x /usr/local/bin/lc
          lc config add --config lyrid_github --key ${{secrets.LYRID_KEY}} --secret ${{secrets.LYRID_SECRET}}
          lc code submit --rid apsoutheast1
